export type IconType =
  | 'Email'
  | 'Hamburger'
  | 'ArrowBottomRight'
  | 'Linkedin'
  | 'Codepen'
  | 'Codesandbox'
  | 'ArrowLeft'
  | 'ArrowRight'
  | 'ArrowDown'
  | 'ArrowUp'
  | 'CheckMark'
  | 'Check'
  | 'Warning'
  | 'ExplanationMark'
